#pragma once


#define TCP_LOCAL_RECV_BUFF_SIZE 1500
#define TCP_REMOTE_RECV_BUFF_SIZE 1500

#define UDP_LOCAL_RECV_BUFF_SIZE 1500
#define UDP_REMOTE_RECV_BUFF_SIZE 1500

#define TCP_BUFFER_SIZE TCP_LOCAL_RECV_BUFF_SIZE
#define UDP_BUFFER_SIZE UDP_LOCAL_RECV_BUFF_SIZE

#define SESSION_TIMEOUT 60
#define TIMER_EXPIRE_TIME 30
